apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-client
  template:
    metadata:
      labels:
        app: fortio-client
    spec:
      containers:
      - name: fortio
        image: fortio/fortio
        ports:
        - containerPort: 8080
        args:
        - server # This starts the UI and the background engine
---
apiVersion: v1
kind: Service
metadata:
  name: fortio-client
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fortio-client
  type: LoadBalancer
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: fortio-http
spec:
  host: fortio-http
  port: 8080
  routingKey: fortio-http
  type: tcp
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: fortio-grpc
spec:
  host: fortio-grpc
  port: 8079
  routingKey: fortio-grpc
  type: tcp
